openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: API for managing products.

servers:
  - url: http://localhost:3000

paths:
  /products:
    post:
      summary: Add a new product
      operationId: addProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the product
                category:
                  type: string
                  description: The category of the product
                description:
                  type: string
                  description: A description of the product
                price:
                  type: number
                  format: float
                  description: The price of the product
                imageUrl:
                  type: string
                  description: The URL of the product image
              required:
                - name
                - category
                - description
                - price
                - imageUrl
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

    get:
      summary: Retrieve all products
      operationId: getAllProducts
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /search:
    get:
      summary: Search for products by name
      operationId: searchProducts
      parameters:
        - name: term
          in: query
          required: true
          description: The search term
          schema:
            type: string
      responses:
        '200':
          description: A list of matching products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          description: The name of the product
        category:
          type: string
          description: The category of the product
        description:
          type: string
          description: A description of the product
        price:
          type: number
          format: float
          description: The price of the product
        imageUrl:
          type: string
          description: The URL of the product image
      required:
        - id
        - name
        - category
        - description
        - price
        - imageUrl
